package problems1to5;

import java.util.ArrayList;
import java.util.List;

/* 
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million (parameter maxNumber), find the sum of the even-valued terms.
 * 
 */

public class EvenFibonacciNumbers {

	private static List<Integer> fiboArray  = new ArrayList<Integer>();
	private static int validElements = 0;

	private static int i = 1; 

	private static int sumOfEvenElements = 0;
	
	
	public static void fiboArray(int maxNumber) {
		System.out.println("EXERCISE 2: Even Fibonacci numbers");
		System.out.println();
		System.out.println("Fibonacci numbers that do not exceed " + maxNumber + " : ");
		System.out.println();
		
		fiboArray.add(1);
		fiboArray.add(2);
		
		do {
		fiboArray.add(fiboArray.get(i-1) + fiboArray.get(i));
		 			
				i++;
				
				//  trackExecution();  // debugging tool
		}
		while (fiboArray.get(i) < maxNumber); 
			
			fiboArray.remove(i);
			validElements = i;
				
		
		// output: 
		printList(fiboArray);
		
		sum();
		
		System.out.println();
		System.out.println("Elements: " + validElements);
		
		System.out.println();
		System.out.println("Sum of even elements: " + sumOfEvenElements);
		
		
	}

	
	// sum
	private static void sum() {
		for (int k = 0; k < i ; k++)
			if (fiboArray.get(k) % 2 == 0)
				sumOfEvenElements += fiboArray.get(k);
	}
	
	// print 
	public static void printList(List<Integer> list) {
		for(int x : list) 
			System.out.print(x + " ");
	}
	
	// debugging tool
	private static void trackExecution() {
		System.out.println("i = " + i);
		System.out.print("Fibo - 2 = " + fiboArray.get(i-2)  + " ");
		System.out.println();
		System.out.print("Fibo - 1 = " +  fiboArray.get(i-1)+  " ");
		System.out.println();
			
		System.out.print("Fibo = " + fiboArray.get(i)+ " ");
		System.out.println();
		System.out.println();
	}
	
	
}
