package problems1to5;

import java.util.ArrayList;
import java.util.List;

/* 
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million (parameter maxNumber), find the sum of the even-valued terms.
 * 
 */

public class EvenFibonacciNumbers {

	private static List<Integer> fiboArray  = new ArrayList<Integer>();
	private static int validElements = 0;

	private static int i = 1; 
	private static int first;
	private static int second;
	private static int current;
	
	private static int sumOfEvenElements = 0;
	
	public static void fiboArray(int maxNumber) {
		
		
		fiboArray.add(1);
		fiboArray.add(2);
		current = 0;
		
		first = fiboArray.get(0);
		second = fiboArray.get(1);
		
		while (current < maxNumber) {
			
			i++;
			
			fiboArray.add(first + second);
			if (fiboArray.get(i) > maxNumber) {
				fiboArray.remove(i);
				validElements = i;
				break;
			}
			current = fiboArray.get(i);
			first = second;
			second = fiboArray.get(i);
		
			 trackExecution();  // debugging tool
		
		}
		
		printList(fiboArray);
		
		sum();
		
		System.out.println();
		System.out.println("Sum of even elements: " + sumOfEvenElements);
		
	}

	
	private static void sum() {
		for (int k = 0; k < i ; k++)
			if (fiboArray.get(k) % 2 == 0)
				sumOfEvenElements += fiboArray.get(k);
	}
	
	// print 
	public static void printList(List<Integer> list) {
		for(int x : list) 
			System.out.print(x + " ");
	}
	
	// debugging tool
	private static void trackExecution() {
		System.out.println("i = " + i);
		System.out.print("Fibo - 2 = " + first + " ");
		System.out.println();
		System.out.print("Fibo - 1 = " + second + " ");
		System.out.println();
			
		System.out.print("Fibo = " + current + " ");
		System.out.println();
	}
	
	
}
